
$mostlyopaque
$ambientboost
$staticprop

$modelname jessev92/props_amuse/amuse_3d

$model Sky amuse_3d_ref

$surfaceprop nodecal

$illumposition 17.755 18.165 326.573

$cdmaterials models/jessev92/props_amuse
$cdmaterials models/jessev92/props_amusement
$cdmaterials models/props_amusement

$sequence idle amuse_3d_ref loop

$collisionmodel amuse_3d_physics
{

	$mass 128
	$inertia 1
	$damping 0
	$rotdamping 0
	$rootbone " "

}
